name: app_base_client
description: A starting point for Dart libraries or applications.
version: 1.0.2
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  fixnum: ^1.1.1
  grpc: ^5.0.0
  protobuf: ^5.1.0
  # path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  protoc_plugin: ^24.0.0
  test: ^1.25.6
